# Generated by Django 2.0 on 2018-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('damage_bonus', models.FloatField(null=True)),
                ('damage_dice', models.CharField(max_length=20, null=True)),
                ('attack_bonus', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('alignment', models.CharField(max_length=100)),
                ('armor_class', models.FloatField()),
                ('hit_points', models.FloatField()),
                ('speed', models.CharField(max_length=50)),
                ('strength', models.FloatField(null=True)),
                ('dexterity', models.FloatField(null=True)),
                ('constitution', models.FloatField(null=True)),
                ('intelligence', models.FloatField(null=True)),
                ('wisdom', models.FloatField(null=True)),
                ('charisma', models.FloatField(null=True)),
                ('medicine', models.FloatField(null=True)),
                ('religion', models.FloatField(null=True)),
                ('damage_vulnerabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_resistances', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_immunities', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_immunities', models.CharField(blank=True, max_length=100, null=True)),
                ('senses', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_rating', models.FloatField(null=True)),
                ('actions', models.ManyToManyField(null=True, to='monsters.Action')),
                ('special_abilities', models.ManyToManyField(null=True, to='skills.SpecialAbility')),
            ],
        ),
    ]
